# Create your first Project

## Introduction

Create your first project is not complicated, the project provides a `Template project`
using `Gradle` but you could create a new project from Scratch too.

The advantages of the usage of the Template project are:

 * Build System configured
 * Dependencies defined
 * Tasks defined for the interaction with the Brick

## Create your first project using the Gradle template project

The project provide a Gradle template project ready to run in your favourite Java IDE like IntelliJ or Eclipse.

Visit this link:https://github.com/ev3dev-lang-java/template_project_gradle[Git repository] to download the template project:

```
git clone https://github.com/ev3dev-lang-java/template_project_gradle.git
```

Once you have downloaded the project in your personal computer,
open the project with your Java IDE to edit the file: `config.gradle`: to update IP of you Brick:


```
remotes {
    ev3dev {
        host = '10.0.1.3'
        user = 'robot'
        password = 'maker'
    }
}
```

to check that the java IDE connect with the brick, execute the following Gradle task:

```
./gradlew testConnection
```

The project are configured to send to the Brick the following example:

[source,java]
----
include::MyFirstRobot.java[]
----

The example was designed to move a mobile robot with 2 motors connected to Port A & Port B.

### Deploy your program

To deploy the example on your brick, open a `terminal` and type:

```
./gradlew deployAndRun
```

## Create your first project from scratch

Another alternative is the creation of a project from Scratch using Maven/Gradle.

To start a new project with this library, add the following repository and dependency.

```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```

``` xml
<dependency>
    <groupId>com.github.ev3dev-lang-java</groupId>
    <artifactId>ev3dev-lang-java</artifactId>
    <version>0.7.0</version>
</dependency>
```
	
Further information about link:https://jitpack.io/#ev3dev-lang-java/ev3dev-lang-java/0.7.0[the dependency]

## Playing with more examples

The project has a repository with several examples about the usage of the different libraries.

Visit the link:https://github.com/ev3dev-lang-java/examples[repository about examples] to download and test more examples.

## The Next Step

Continue with the next section about: link:../#fundamentals-of-robotics[Fundamentals of Robotics]

++++

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-343143-18', 'auto');
    ga('send', 'pageview');
</script>
++++
