# Getting Started with your personal computer

## The modern Java development environment for Windows

#### Package manager

Windows has a popular package manager named link:https://chocolatey.org[Choco]. I recommend to read
the link:https://chocolatey.org/docs/commands-reference[technical documentation] and install it.

To install openJDK in your computer with Choco, type:

[source]
----
choco install jdk8
----

WARNING: In the future, we will recommend the installation of OpenJDK 11, but at the moment, we detect an issue between OpenJDK
& Gradle, so I prefer to recommend to install Java 8.

To install OpenJDK 11:

[source]
----
choco install openjdk
----

#### Java Virtual Machine

To program with Java is necessary to install in your laptop a Java Development Kit (JDK).

A Java Development Kit (JDK) is a program development environment
for writing Java applications. It consists of a runtime environment that "sits on top" of the operating system layer
as well as the tools and programming that developers need to compile, debug, and run applications
written in the Java language.

Once you have installed Java JDK, check the installation:

[source]
----
java -version
----

You should view the following output:

[source]
----
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) Client VM (build 25.181-b13, mixed mode)
----

To check if you are able to compile Java files,
create a new file with the name of `HelloWorld.java` and copy and paste on it the following content:

[source,java]
----
include::./HelloWorld.java[]
----

Save the file and open in a terminal to type the following commands:

``` java
javac HelloWorld.java
java HelloWorld
```

You should read: `HelloWorld` in the terminal.

Further information about link:https://openjdk.java.net/[OpenJDK]

#### Build Systems

Modern Java development use dependencies stored on Software Repositories.
It is a good idea if you install the popular build Systems as `Maven` & `Gradle` for Java.
This project is modular and it deliver multiple dependencies.

Using choco, it is possible install Maven & Gradle easily:

[source]
----
choco install maven
choco install gradle
----

Further information about link:https://maven.apache.org/[Maven] &amp; https://gradle.org/[Gradle].

### Java IDE

To develop a single Java file, maybe you could use a simple Text Editor
but current Java IDE offers several funcionalities to
help you in the process to develop software with Java. In the market, the most popular Java IDE are `IntelliJ` & `Eclipse`.

[source]
----
choco install intellijidea-community
choco install eclipse
----

Further information about link:https://www.jetbrains.com/idea/[IntelliJ] & link:http://www.eclipse.org/[Eclipse]

### Source Control Management

Git is a popular technology to manage code. Many ideas that you see on Internet are stored on
Git repositories so manage this technology is necessary.

You could use the Version control features from link:https://www.jetbrains.com/help/idea/version-control-integration.html[IntelliJ]
or use a dedicated tool like link:https://www.sourcetreeapp.com/[SourceTree]

++++

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-343143-18', 'auto');
    ga('send', 'pageview');
</script>
++++