# Getting Started with your personal computer

## Requirements

### Java

To program, with Java, it is necessary to install in your laptop Java JDK.
To begin any Java development, you need to be installed Java. 

*OSX:*

[source]
----
brew update
brew tap caskroom/cask
brew install Caskroom/cask/java
----

Further information about Java: https://www.java.com/es/about/whatis_java.jsp[https://www.java.com/es/about/whatis_java.jsp]

### Maven/Gradle

Modern Java development use dependencies stored on Software Repositories.
It is a good idea if you install the popular Build Systems as `Maven` & `Gradle`

*OSX:*

[source]
----
brew install maven
brew install gradle
----

Further information about Maven &amp; Gradle:
https://maven.apache.org/[https://maven.apache.org/]
https://gradle.org/[https://gradle.org/]

### Git

Git is a popular technology to manage code. Many ideas that you see on Internet are stored on
Git repositories so manage this technology is necessary.
Besides, the project includes some project templates to help you in the process to have your first project
ready to use with your brick.


Install a visual Git Client to download this repository.
https://www.sourcetreeapp.com/[https://www.sourcetreeapp.com/]

### Java IDE


To develop any Java file, with a text editor is enough but the right way to develop Java programs is using a Modern IDE
like `IntelliJ` or `Eclipse`

Install a Java IDE to develop Java Software
https://www.jetbrains.com/idea/[https://www.jetbrains.com/idea/]

## Test your local environment

Once, you have installed everything, it is necessary to verify that everything goes well.

Create a file with the name of HelloWorld.java and copy and paste on it the following content:

[source,java]
----
include::./HelloWorld.java[]
----

Later, open a terminal and type:

``` java
javac HelloWorld.java
java HelloWorld
```

You should read: `HelloWorld` if the answer is **Yes**, your installation process on your
personal computer has finished.

++++

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-343143-18', 'auto');
    ga('send', 'pageview');
</script>
++++