# Getting Started on your computer

## Install/Update your development environment

### Install Java

To begin any Java development, you need to be installed Java. 

*OSX:*

[source]
----
brew update
brew tap caskroom/cask
brew install Caskroom/cask/java
----

Further information about Java: https://www.java.com/es/about/whatis_java.jsp[https://www.java.com/es/about/whatis_java.jsp]

### Install Maven/Gradle

*OSX:*

[source]
----
brew install maven
brew install gradle
----

Further information about Maven &amp; Gradle:
https://maven.apache.org/[https://maven.apache.org/]
https://gradle.org/[https://gradle.org/]

### Install a Git Client

Install a visual Git Client to download this repository.
https://www.sourcetreeapp.com/[https://www.sourcetreeapp.com/]

### Install a Java IDE

Install a Java IDE to develop Java Software
https://www.jetbrains.com/idea/[https://www.jetbrains.com/idea/]

## Test your local environment

Once, you have installed everything, it is necessary to verify that everything goes well.

Create a file with the name of HelloWorld.java and copy and paste on it the following content:

[source,java]
----
include::./HelloWorld.java[]
----

Later, open a terminal and type:

``` java
javac HelloWorld.java
java HelloWorld
```

You should read: `HelloWorld` if the answer is **Yes**, your installation process on your
personal computer has finished.